import type { Recipe } from '../types';

/** Recettes de base ; les grammages sont ensuite mis à l'échelle par le générateur. */
export const RECIPES: Recipe[] = [
  {
    id: 'r_chicken_rice_broc',
    name: 'Poulet, riz basmati & brocoli',
    ingredients: [
      { foodId: 'chicken_breast', grams: 150 },
      { foodId: 'rice', grams: 180 },
      { foodId: 'broccoli', grams: 200 },
      { foodId: 'olive_oil', grams: 8 },
    ],
    prepMinutes: 20,
    cost: 2,
    tags: ['high_protein', 'meal_prep'],
    slots: ['lunch', 'dinner'],
    steps: ['Cuire le riz.', 'Saisir le poulet en lamelles 6–8 min.', 'Brocoli vapeur 6 min, filet d’huile d’olive.'],
  },
  {
    id: 'r_omelette',
    name: 'Omelette 3 œufs, épinards & pain complet',
    ingredients: [
      { foodId: 'egg', grams: 165 },
      { foodId: 'spinach', grams: 100 },
      { foodId: 'bread_whole', grams: 60 },
    ],
    prepMinutes: 10,
    cost: 1,
    tags: ['quick', 'budget', 'vegetarian'],
    slots: ['breakfast', 'lunch', 'dinner'],
    steps: ['Faire tomber les épinards à la poêle.', 'Ajouter les œufs battus, cuire 3 min.', 'Servir avec le pain.'],
  },
  {
    id: 'r_skyr_bowl',
    name: 'Bowl skyr, avoine & fruits rouges',
    ingredients: [
      { foodId: 'skyr', grams: 200 },
      { foodId: 'oats', grams: 40 },
      { foodId: 'berries', grams: 100 },
      { foodId: 'honey', grams: 8 },
    ],
    prepMinutes: 3,
    cost: 1,
    tags: ['quick', 'high_protein', 'vegetarian', 'budget'],
    slots: ['breakfast', 'snack'],
    steps: ['Tout mélanger dans un bol.'],
  },
  {
    id: 'r_tuna_pasta',
    name: 'Pâtes complètes au thon & sauce tomate',
    ingredients: [
      { foodId: 'pasta_wholegrain', grams: 200 },
      { foodId: 'tuna_can', grams: 112 },
      { foodId: 'tomato_sauce', grams: 120 },
      { foodId: 'emmental', grams: 15 },
    ],
    prepMinutes: 15,
    cost: 1,
    tags: ['budget', 'high_protein', 'quick'],
    slots: ['lunch', 'dinner'],
    steps: ['Cuire les pâtes.', 'Chauffer la sauce avec le thon émietté.', 'Mélanger, parsemer de fromage.'],
  },
  {
    id: 'r_salmon_potato',
    name: 'Saumon, pommes de terre & haricots verts',
    ingredients: [
      { foodId: 'salmon', grams: 125 },
      { foodId: 'potato', grams: 250 },
      { foodId: 'green_beans', grams: 200 },
    ],
    prepMinutes: 25,
    cost: 3,
    tags: ['high_protein', 'gourmet'],
    slots: ['lunch', 'dinner'],
    steps: ['Pommes de terre à l’eau 20 min.', 'Saumon au four 12 min à 200 °C.', 'Haricots verts vapeur.'],
  },
  {
    id: 'r_lentil_curry',
    name: 'Curry de lentilles, riz & épinards',
    ingredients: [
      { foodId: 'lentils', grams: 220 },
      { foodId: 'rice', grams: 120 },
      { foodId: 'spinach', grams: 100 },
      { foodId: 'tomato_sauce', grams: 100 },
      { foodId: 'olive_oil', grams: 5 },
    ],
    prepMinutes: 25,
    cost: 1,
    tags: ['vegetarian', 'budget', 'meal_prep'],
    slots: ['lunch', 'dinner'],
    steps: ['Revenir les épices dans l’huile.', 'Ajouter lentilles, sauce tomate, épinards, mijoter 10 min.', 'Servir avec le riz.'],
  },
  {
    id: 'r_tofu_stirfry',
    name: 'Wok tofu, légumes & quinoa',
    ingredients: [
      { foodId: 'tofu', grams: 180 },
      { foodId: 'mixed_veg', grams: 250 },
      { foodId: 'quinoa', grams: 150 },
      { foodId: 'soy_sauce', grams: 15 },
    ],
    prepMinutes: 20,
    cost: 2,
    tags: ['vegetarian', 'high_protein', 'meal_prep'],
    slots: ['lunch', 'dinner'],
    steps: ['Dorer le tofu en dés.', 'Ajouter les légumes, sauter 5 min.', 'Sauce soja, servir sur le quinoa.'],
  },
  {
    id: 'r_turkey_wrap',
    name: 'Wrap dinde, houmous & crudités',
    ingredients: [
      { foodId: 'wrap', grams: 60 },
      { foodId: 'turkey_slice', grams: 90 },
      { foodId: 'hummus', grams: 30 },
      { foodId: 'salad', grams: 40 },
      { foodId: 'tomato', grams: 80 },
    ],
    prepMinutes: 5,
    cost: 2,
    tags: ['quick', 'high_protein'],
    slots: ['lunch', 'snack'],
    steps: ['Tartiner le houmous.', 'Garnir de dinde et crudités, rouler.'],
  },
  {
    id: 'r_beef_sweetpotato',
    name: 'Bœuf 5 %, patate douce & poivrons',
    ingredients: [
      { foodId: 'beef_5', grams: 150 },
      { foodId: 'sweet_potato', grams: 220 },
      { foodId: 'bell_pepper', grams: 150 },
      { foodId: 'olive_oil', grams: 5 },
    ],
    prepMinutes: 25,
    cost: 2,
    tags: ['high_protein', 'meal_prep'],
    slots: ['lunch', 'dinner'],
    steps: ['Rôtir la patate douce en cubes 20 min.', 'Saisir le bœuf et les poivrons.', 'Assembler.'],
  },
  {
    id: 'r_overnight_oats',
    name: 'Overnight oats protéinés',
    ingredients: [
      { foodId: 'oats', grams: 60 },
      { foodId: 'milk', grams: 200 },
      { foodId: 'whey', grams: 25 },
      { foodId: 'banana', grams: 100 },
      { foodId: 'chia', grams: 10 },
    ],
    prepMinutes: 5,
    cost: 1,
    tags: ['meal_prep', 'high_protein', 'budget', 'vegetarian'],
    slots: ['breakfast'],
    steps: ['Mélanger le soir dans un bocal.', 'Laisser au frais la nuit, ajouter la banane le matin.'],
  },
  {
    id: 'r_chickpea_salad',
    name: 'Salade pois chiches, feta & concombre',
    ingredients: [
      { foodId: 'chickpeas', grams: 200 },
      { foodId: 'feta', grams: 50 },
      { foodId: 'cucumber', grams: 150 },
      { foodId: 'tomato', grams: 120 },
      { foodId: 'olive_oil', grams: 8 },
    ],
    prepMinutes: 10,
    cost: 1,
    tags: ['vegetarian', 'quick', 'budget', 'meal_prep'],
    slots: ['lunch', 'dinner'],
    steps: ['Égoutter les pois chiches.', 'Couper les légumes et la feta.', 'Assaisonner.'],
  },
  {
    id: 'r_cod_semolina',
    name: 'Cabillaud, semoule & courgettes',
    ingredients: [
      { foodId: 'white_fish', grams: 160 },
      { foodId: 'semolina', grams: 160 },
      { foodId: 'zucchini', grams: 200 },
      { foodId: 'olive_oil', grams: 8 },
    ],
    prepMinutes: 20,
    cost: 2,
    tags: ['high_protein'],
    slots: ['lunch', 'dinner'],
    steps: ['Cabillaud en papillote 15 min.', 'Semoule hydratée 5 min.', 'Courgettes poêlées.'],
  },
  {
    id: 'r_shrimp_rice',
    name: 'Riz sauté aux crevettes & œuf',
    ingredients: [
      { foodId: 'shrimp', grams: 150 },
      { foodId: 'rice', grams: 180 },
      { foodId: 'egg', grams: 55 },
      { foodId: 'mixed_veg', grams: 150 },
      { foodId: 'soy_sauce', grams: 10 },
    ],
    prepMinutes: 15,
    cost: 3,
    tags: ['high_protein', 'gourmet', 'quick'],
    slots: ['lunch', 'dinner'],
    steps: ['Sauter légumes et crevettes.', 'Ajouter le riz cuit puis l’œuf brouillé.', 'Sauce soja.'],
  },
  {
    id: 'r_pizza_salad',
    name: 'Pizza maison & grande salade',
    ingredients: [
      { foodId: 'pizza', grams: 200 },
      { foodId: 'salad', grams: 100 },
      { foodId: 'turkey_slice', grams: 40 },
    ],
    prepMinutes: 20,
    cost: 2,
    tags: ['gourmet'],
    slots: ['dinner'],
    steps: ['Cuire la pizza.', 'Servir avec une grande salade et la dinde.'],
  },
  {
    id: 'r_cottage_toast',
    name: 'Tartines cottage cheese, avocat & œuf',
    ingredients: [
      { foodId: 'bread_whole', grams: 70 },
      { foodId: 'cottage', grams: 100 },
      { foodId: 'avocado', grams: 50 },
      { foodId: 'egg', grams: 55 },
    ],
    prepMinutes: 8,
    cost: 2,
    tags: ['quick', 'vegetarian', 'gourmet'],
    slots: ['breakfast', 'lunch'],
    steps: ['Griller le pain.', 'Tartiner cottage et avocat.', 'Ajouter l’œuf mollet (6 min).'],
  },
  {
    id: 'r_protein_snack',
    name: 'Collation fromage blanc, banane & amandes',
    ingredients: [
      { foodId: 'fromage_blanc', grams: 200 },
      { foodId: 'banana', grams: 100 },
      { foodId: 'almonds', grams: 15 },
    ],
    prepMinutes: 2,
    cost: 1,
    tags: ['quick', 'budget', 'high_protein', 'vegetarian'],
    slots: ['snack', 'breakfast'],
    steps: ['Tout mettre dans un bol.'],
  },
  {
    id: 'r_tempeh_bowl',
    name: 'Bowl tempeh, patate douce & avocat',
    ingredients: [
      { foodId: 'tempeh', grams: 120 },
      { foodId: 'sweet_potato', grams: 180 },
      { foodId: 'avocado', grams: 50 },
      { foodId: 'spinach', grams: 80 },
    ],
    prepMinutes: 25,
    cost: 3,
    tags: ['vegetarian', 'gourmet', 'meal_prep'],
    slots: ['lunch', 'dinner'],
    steps: ['Rôtir la patate douce.', 'Dorer le tempeh.', 'Assembler sur les épinards avec l’avocat.'],
  },
  {
    id: 'r_bean_chili',
    name: 'Chili sin carne',
    ingredients: [
      { foodId: 'red_beans', grams: 200 },
      { foodId: 'tomato_sauce', grams: 150 },
      { foodId: 'bell_pepper', grams: 100 },
      { foodId: 'rice', grams: 150 },
      { foodId: 'pea_protein', grams: 20 },
    ],
    prepMinutes: 30,
    cost: 1,
    tags: ['vegetarian', 'budget', 'meal_prep', 'high_protein'],
    slots: ['lunch', 'dinner'],
    steps: ['Mijoter haricots, sauce et poivrons 15 min.', 'Incorporer la protéine de pois.', 'Servir avec le riz.'],
  },
  {
    id: 'r_ham_potato',
    name: 'Jambon, purée maison & haricots verts',
    ingredients: [
      { foodId: 'ham', grams: 100 },
      { foodId: 'potato', grams: 250 },
      { foodId: 'milk', grams: 50 },
      { foodId: 'green_beans', grams: 200 },
    ],
    prepMinutes: 25,
    cost: 1,
    tags: ['budget'],
    slots: ['lunch', 'dinner'],
    steps: ['Écraser les pommes de terre avec le lait.', 'Haricots vapeur.', 'Servir avec le jambon.'],
  },
  {
    id: 'r_choco_porridge',
    name: 'Porridge chocolat & beurre de cacahuète',
    ingredients: [
      { foodId: 'oats', grams: 60 },
      { foodId: 'soy_milk', grams: 250 },
      { foodId: 'dark_chocolate', grams: 10 },
      { foodId: 'peanut_butter', grams: 15 },
      { foodId: 'pea_protein', grams: 20 },
    ],
    prepMinutes: 7,
    cost: 1,
    tags: ['gourmet', 'quick', 'vegetarian', 'high_protein'],
    slots: ['breakfast', 'snack'],
    steps: ['Cuire l’avoine dans la boisson soja 4 min.', 'Ajouter protéine, chocolat et beurre de cacahuète.'],
  },
];
